### ISSUE TITLE
la variable POPCORN_BASE_URL et POPCORN_SLACK_WEBHOOK ne sont pas renseignées : image de partage et contact non fonctionnel

### ISSUE THREAD

**Issue by yann-yinn** [popcorn-rennes/popcorn-rennes#3]
Hello ! 
Côté Travis il faut renseigner les variables présentes dans le fichier `.env.example`, je viens de l'ajouter dans le README . Ca fait partie des choses qui seront bientôt détectées par les tests https://github.com/popcorn-nantes/popcorn-machine/pull/35

**Comment by gurvanhenry** [comment]
Merci pour l'issue.

J'ai défini POPCORN_BASE_URL dans Travis. 
=> aperçu profil dans discussion social OK

J'ai créé une slack app et défini POPCORN_SLACK_WEBHOOK dans Travis.
=> message posté sur le site bien reçu sur slack.

👍
